### ISSUE TITLE
Problem with openmc-plotter

### ISSUE THREAD

**Issue by Ilyavitte** [openmc-dev/plotter#85] opened 2022-04-20 09:21 UTC
Hello! I try to start openmc-plotter, but have error - 
Traceback (most recent call last): 
  File "signature_bootstrap.py", line 110, in bootstrap 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/posixpath.py", line 152, in dirname 
    p = os.fspath(p) 
TypeError: expected str, bytes or os.PathLike object, not NoneType 
SystemError: could not initialize part 2 
 
The above exception was the direct cause of the following exception: 
 
Traceback (most recent call last): 
  File "/home/ilya/anaconda3/envs/openmc-env1/bin/openmc-plotter", line 5, in <module> 
    from openmc_plotter.__main__ import main 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/openmc_plotter/__main__.py", line 11, in <module> 
    from .main_window import MainWindow, _openmcReload 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/openmc_plotter/main_window.py", line 14, in <module> 
    import openmc 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/openmc/__init__.py", line 1, in <module> 
    from openmc.arithmetic import * 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/openmc/arithmetic.py", line 4, in <module> 
    import numpy as np 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module> 
    from . import core 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module> 
    from . import multiarray 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/numpy/core/multiarray.py", line 81, in <module> 
    def empty_like(prototype, dtype=None, order=None, subok=None, shape=None): 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/numpy/core/overrides.py", line 201, in decorator 
    return array_function_dispatch( 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/site-packages/numpy/core/overrides.py", line 178, in decorator 
    def public_api(*args, **kwargs): 
  File "/home/ilya/anaconda3/envs/openmc-env1/lib/python3.10/functools.py", line 52, in update_wrapper 
    value = getattr(wrapped, attr) 
SystemError: <method-wrapper '__get__' of getset_descriptor object at 0x7fb5dfaf79c0> returned a result with an exception set

And maybe we help me with other one. I dont understand, why i cant use openmcdiscussionforum. My name - ilyavitte. When I try to make some topic, i see message - permission denied. Why?

**Comment by kkiesling** [comment] 2022-04-20 15:26
Can you provide more detail about what operating system you are using, how you installed the plotter (was it source or from pip), and what command you are running that causes this error?

**Comment by pshriwise** [comment] 2022-04-20 15:30
Hi @Ilyavitte, sorry you're running into this problem. From the traceback, it looks like it may have something to do with your numpy installation. If you run `python -c "import numpy as np"` from your terminal, does that result in an error as well?

As for the discussion forum, it's odd that you can't create a new topic there. Can you send me a message (username pshriwise) on the forum so we can dig into that more?

**Comment by Ilyavitte** [comment] 2022-04-20 16:19
I use wsl. In it i have conda environment. In it i use pip install openmc-plotter . Then i go in folder with my file and .xml files for it. And then  I type openmc-plotter. Now i cant use these two commands you written, cause im not in workplace, but i use numpy in my codes in this environment and it works. I try to send you a message, but “ Sorry, you cannot send a personal message to that user.”

**Comment by Ilyavitte** [comment] 2022-04-25 06:51
> Hi @Ilyavitte, sorry you're running into this problem. From the traceback, it looks like it may have something to do with your numpy installation. If you run `python -c "import numpy as np"` from your terminal, does that result in an error as well?
> 
> As for the discussion forum, it's odd that you can't create a new topic there. Can you send me a message (username pshriwise) on the forum so we can dig into that more?

I try this command and it works normally

**Comment by kkiesling** [comment] 2022-04-25 16:58
Can you share the output of `conda list` for this environment? I just made a clean environment with openmc and the plotter and was able to launch a model just fine.

**Comment by Ilyavitte** [comment] 2022-04-28 11:44
When i try to make new environment, i have this:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1059, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 291, in get_reduced_index
        push_record(record)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 265, in push_record
        combined_depends = record.combined_depends
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 478, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 478, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 509, in _merge
        final = this_component.merge(that_component)
      File "/home/ilya/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 761, in merge
        % (self.raw_value, other.raw_value))
    ValueError: Incompatible component merge:
      - 'mpi_mpich_*'
      - 'mpi_mpich_tempest*'

`$ /home/ilya/anaconda3/bin/conda create -n new openmc`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/ilya/anaconda3/bin/conda
         CONDA_PYTHON_EXE=/home/ilya/anaconda3/bin/python
               CONDA_ROOT=/home/ilya/anaconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/ilya/anaconda3/bin:/home/ilya/.local/bin:/home/ilya/bin:/home/il
                          ya/anaconda3/bin:/home/ilya/anaconda3/condabin:/usr/local/sbin:/usr/lo
                          cal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr
                          /lib/wsl/lib:/mnt/c/ProgramData/Anaconda3:/mnt/c/ProgramData/Anaconda3
                          /Library/mingw-w64/bin:/mnt/c/ProgramData/Anaconda3/Library/usr/bin:/m
                          nt/c/ProgramData/Anaconda3/Library/bin:/mnt/c/ProgramData/Anaconda3/Sc
                          ripts:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/W
                          bem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/Syst
                          em32/OpenSSH:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/P
                          rogramData/DockerDesktop/version-bin:/mnt/c/Users/bedretdinov/anaconda
                          3:/mnt/c/Users/bedretdinov/anaconda3/Library/mingw-w64/bin:/mnt/c/User
                          s/bedretdinov/anaconda3/Library/usr/bin:/mnt/c/Users/bedretdinov/anaco
                          nda3/Library/bin:/mnt/c/Users/bedretdinov/anaconda3/Scripts:/mnt/c/Use
                          rs/bedretdinov/AppData/Local/Programs/Python/Python310/Scripts:/mnt/c/
                          Users/bedretdinov/AppData/Local/Programs/Python/Python310:/mnt/c/Users
                          /bedretdinov/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/bedretdi
                          nov/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/ilya/.condarc
 populated config files : /home/ilya/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.0.final.0
       virtual packages : __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ilya/anaconda3  (writable)
      conda av data dir : /home/ilya/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ilya/anaconda3/pkgs
                          /home/ilya/.conda/pkgs
       envs directories : /home/ilya/anaconda3/envs
                          /home/ilya/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.0 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by Ilyavitte** [comment] 2022-04-28 11:45
conda list :
# packages in environment at /home/ilya/anaconda3/envs/openmc-env1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h5764c6d_2    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8       py310hff52083_2    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
curl                      7.82.0               h2283fc2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dagmc                     3.2.1                h27087fc_4    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.0           py310hd8f1fbe_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.32.0          py310h5764c6d_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2          py310hff52083_5    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gst-plugins-base          1.20.1               hcf0ee16_1    conda-forge
gstreamer                 1.20.1               hd4edc92_1    conda-forge
h5py                      3.6.0           nompi_py310he751f51_100    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
importlib-metadata        4.11.3          py310hff52083_1    conda-forge
importlib_resources       5.7.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.13.0          py310hfdc917e_0    conda-forge
ipython                   8.2.0           py310hff52083_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1          py310hff52083_1    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0           py310hff52083_7    conda-forge
jupyter_client            7.2.2              pyhd8ed1ab_1    conda-forge
jupyter_console           6.4.3              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2           py310hff52083_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.2           py310hbf28c38_1    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libcurl                   7.82.0               h2283fc2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 h676c864_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libxslt                   1.1.33               h0ef7038_3    conda-forge
libzip                    1.8.0                h1c5bbd1_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lxml                      4.8.0           py310h5764c6d_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
matplotlib                3.5.1           py310hff52083_0    conda-forge
matplotlib-base           3.5.1           py310h23f4a51_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mistune                   0.8.4           py310h6acc77f_1005    conda-forge
moab                      5.3.1           nompi_tempest_py310h9511454_3    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.28               h26416b9_3    conda-forge
mysql-libs                8.0.28               hbc51c84_3    conda-forge
nbclient                  0.6.0              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.77                 h2350873_0    conda-forge
numpy                     1.22.3          py310h45f3432_2    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmc                    0.13.0          dagmc_py310hf9b27c0_101    conda-forge
openmc-plotter            0.2.0                    pypi_0    pypi
openssl                   3.0.2                h166bdaf_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2           py310h769672d_1    conda-forge
pandoc                    2.18                 ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.0           py310he619898_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
prompt_toolkit            3.0.29               hd8ed1ab_0    conda-forge
psutil                    5.9.0           py310h5764c6d_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
pyside2                   5.13.2          py310hcea3d2e_8    conda-forge
python                    3.10.4          h2660328_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyzmq                     22.3.0          py310h330234f_2    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
qtconsole                 5.3.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.0              pyhd8ed1ab_0    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.8.0           py310hea5193d_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                62.1.0          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
tempest-remap             2.1.1                hfda0864_0    conda-forge
terminado                 0.13.3          py310hff52083_1    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1             py310h5764c6d_3    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
uncertainties             3.1.6              pyhd8ed1ab_0    conda-forge
unicodedata2              14.0.0          py310h5764c6d_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.0           py310hff52083_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

**Comment by kkiesling** [comment] 2022-04-28 14:27
@Ilyavitte this is a known issue with one of OpenMC's dependency's we are trying to resolve still. It does work to install with `mamba` instead of `conda` though (`mamba install -c conda-forge openmc`)

If you don't have mamba, you can install it with `conda install -c conda-forge mamba`. It is basically conda, but seemingly more reliable.

**Comment by kkiesling** [comment] 2022-04-28 16:43
Alright, so I tried my best to reproduce this error but was still unsuccessful. What I did:

- updated my base environment
- created a new env from the base
- `mamba install -c conda-forge openmc`
- `pip3 intall openmc-plotter`

And I was still able to launch fine. The only difference I can see is that you are on `numpy 1.22.3` whereas my update only updated it to `numpy 1.21.5`.

**Comment by paulromano** [comment] 2022-04-29 11:39
@Ilyavitte Sorry you were having trouble on the Discourse forum. Your account there should be fixed now.

**Comment by paulromano** [comment] 2024-06-19 21:22
Closing this issue as stale. @Ilyavitte if you have further issues with the plotter, please feel free to open a new issue or post a message on the OpenMC [user's forum](https://openmc.discourse.group/)

**Closed as completed by paulromano** 2024-06-19 21:22 UTC
